name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)

on:
  pull_request:
  push:
    branches: ['master','series/2.x']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6.4.4
      - name: Lint code
        run: sbt check

  website:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6.4.4
      - name: Check Document Generation
        run: sbt docs/compileDocs

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['17']
        scala: ['2.12.17', '2.13.11', '3.3.1']
        platform: ['JVM', 'Native', 'JS']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6.4.4
      - name: Install libuv
        if: matrix.platform == 'Native'
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        if: matrix.platform == 'JS'
        with:
          node-version: 21.6.1
      - name: Run tests
        run: sbt ++${{ matrix.scala }} zioProcess${{ matrix.platform }}/test

  ci:
    runs-on: ubuntu-22.04
    needs: [lint, website, test]
    steps:
      - name: Aggregate job outcomes
        run: echo "build succeeded"

  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6.4.4
      - name: Release artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
