name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xms2G -Xmx8G -Xss4M -XX:+UseG1GC -XX:ReservedCodeCacheSize=512M -XX:NonProfiledCodeHeapSize=256M # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  SBT_OPTS: -XX:+PrintCommandLineFlags -Xms2G -Xmx8G -Xss4M -XX:+UseG1GC -XX:ReservedCodeCacheSize=512M -XX:NonProfiledCodeHeapSize=256M # Needed for sbt

on:
  pull_request:
  push:
    branches: ['master','series/2.x']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Lint code
        run: sbt check

  website:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.3
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Check Document Generation
        run: sbt docs/compileDocs

  test_scala:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['17']
        scala: ['2.12.x', '2.13.x', '3.3.x']
        platform: ['JVM', 'Native', 'JS']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Install libuv
        if: matrix.platform == 'Native'
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        if: matrix.platform == 'JS'
        with:
          node-version: 21.6.1
      - name: Run tests
        run: sbt ++${{ matrix.scala }} 'zioProcess${{ matrix.platform }}/test'

  test_jvms:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '21' ]
        scala: [ '2.13.x' ]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Run tests
        run: sbt ++${{ matrix.scala }} 'zioProcessJVM/test'


  ci:
    runs-on: ubuntu-latest
    needs: [lint, website, test_scala, test_jvms]
    steps:
      - name: Aggregate job outcomes
        run: echo "build succeeded"

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v7
      - name: Release artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
